### PR TITLE
Added md5 hash of each driver to help find non-identical ones.

### PR DESCRIPTION
**Pull request by paulhagstrom**
Possibly solving a problem we didn't have, but this does an md5 hash of each driver to help ensure that different drivers with identical names, versions, etc., can be discovered. Also, this is done in kind of a clunky way in order to minimize invasiveness. Feel free to refactor.

### CODE REVIEW

**Comment by thecompu** [comment]
Before I add this one, which I think is a good idea in general, I want to understand it a bit more, please. 
I have no experience with the md5 hash functions (or md5 hashing in general) so I might be misunderstanding something...

```
while loop :
    driver = {}
    SOSfile.seek(rel_offset,1)
    driver['comment_start'] = SOSfile.tell()
    # record an md5 hash of the entire driver for comparison
    # initialize a hash on the driver we just reached (which might be an end marker)
    driver['md5'] = hashlib.md5()
```

At this point in the script, the only item recorded is the offset to the beginning of the comment field of a major driver. I see here you're adding an md5 key with an empty value to the dict. 

```
    if drivers_list != []:
        SOSfile.seek(drivers_list[-1]['comment_start'], 0)
        whole_driver = SOSfile.read(driver['comment_start'] - drivers_list[-1]['comment_start'])
        drivers_list[-1]['md5'].update(whole_driver)
        SOSfile.seek(driver['comment_start'], 0)
```

It seems here what you're hashing is just the offset since that's the only item recorded at this point. Is that useful for detecting duplicates? Wouldn't this mean that you can have a near-duplicate whose only difference is in the position inside SOS.DRIVER? Is that what you're after? Or am I misunderstanding? I guess it depends on what type of duplicate you're attempting to detect...?

**Comment by paulhagstrom** [comment]
I don't really have experience with md5 in python either, but from what I gathered from reading the documentation, you initialize an empty hash and then feed it things, and then you can get the resulting digest at the end. So, what I'm doing in my code there is: put a new initialized hash in at the beginning of processing a driver (so, when only the start address is known, but not the end address), then just when we move to a new driver (or end mark), I grab the bytes between the prior driver's start and the current driver's start, and compute the md5 hash by feeding those bytes in. The digest will be computed/revealed at the point of creating the csv file. The second code block you quote above is seeking to the beginning of the prior driver, reading in as many bytes as there are between the current driver's start and the prior driver's start, and then sending them into the hash. So, it is hashing the whole driver block, but should not be dependent on which order it appears within the SOS.DRIVER file, since it excludes the link pointers that connect drivers inside the SOS.DRIVER file.

**Comment by thecompu** [comment]
Yep! I misunderstod it! :-)

**Comment by thecompu** [comment]
By the way, I know you say the code might be clunky but I don't know enough about the hashing to make an informed decision. Maybe I'll try to sort out how to do this more elegantly later but, for now, I want to include your changes. Thanks again.

**Comment by thecompu** [comment]
I've re-re-re-read this and I see what you're getting at here. I think I would do it different , but I don't know what's best. Please explain where I'm wrong.

Part 1:

```
driver['md5'] = hashlib.md5()
```

Create a variable from which you'll access the hashlib.md5() function.

Part 2:

```
    if drivers_list != []:
        SOSfile.seek(drivers_list[-1]['comment_start'], 0)
        whole_driver = SOSfile.read(driver['comment_start'] - drivers_list[-1]['comment_start'])
        drivers_list[-1]['md5'].update(whole_driver)
        SOSfile.seek(driver['comment_start'], 0)
```

If the drivers_list is not empty, go to the previous driver's beginning, read bytes from that point to the beginning of the next driver. Take those bytes and stick it in the dictionary for the previous driver. 

Part 3:

```
    drivers_list[i]['md5'].hexdigest()
```

During CSV writing, hex-digest the bytes written to the md5 entry in part 2.

---

I think that I would do it differently. I'd probably put the hashing into a function in which I'd pass the beginning offsets for the bytes I want to capture and then return the hexdigest. 

I'd also do the hash at the end of the DIB collection, either as part of the DIB collection loop (ideal) or as a separate for-loop (less ideal). I think the reasons are:
1. It uncomplicates the finding of the major offsets. 
2. As I loop to collect DIB information, I'm already resetting my position in the file, so there's no need to pushing data into already passed drivers.
3. It minimizes processing that needs to be done during the CSV write. 

Let me know what you think, please.

**Pull request merged**
